server.port=8081
spring.application.name=postcode-distance
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/wcc_demo
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#-----Logging Config-----#
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

#-----Swagger Config-----#
springdoc.swagger-ui.path=/swagger-ui.html

